# Generated by Django 3.1.4 on 2021-01-23 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0002_auto_20210122_2234'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employee',
            managers=[
            ],
        ),
    ]
